name: "pimcore-skeleton"
services:
  redis:
    image: "redis:alpine"
    command:
      - "redis-server"
      - "--maxmemory"
      - "128mb"
      - "--maxmemory-policy"
      - "volatile-lru"
      - "--save"
      - '""'
    volumes:
      - "redis-data:/data"

  db:
    image: "mariadb:10.11"
    working_dir: "/application"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=1"
    volumes:
      - "database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "ROOT"
      MYSQL_DATABASE: "pimcore"
      MYSQL_USER: "pimcore"
      MYSQL_PASSWORD: "pimcore"

  adminer:
    image: "adminer"
    restart: "always"
    volumes:
      - ".docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/uploads.ini"
    ports:
      - "2001:8080"
    links:
      - "db:db"

  apache:
    image: "httpd:latest"
    ports:
      - "80:80"
    labels:
      - "dev.orbstack.domains=skeleton.orb.local"
    volumes:
      - ".:/usr/local/apache2/htdocs:cached"
      - ".docker/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
    links:
      - "php"
    depends_on:
      - "db"
      - "redis"

  php:
    build: ".docker/php"
    volumes:
      - "~/.composer:/root/composer"
      - ".:/var/www/html:cached"
      - "tmp-storage:/tmp:cached"
      - ".docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini"
    environment:
      COMPOSER_HOME: "/var/www/html"
      PHP_IDE_CONFIG: "serverName=localhost"
      PIMCORE_INSTALL_ADMIN_USERNAME: "admin"
      PIMCORE_INSTALL_ADMIN_PASSWORD: "admin"
      PIMCORE_INSTALL_MYSQL_HOST_SOCKET: "db"
      PIMCORE_INSTALL_MYSQL_PORT: 3306
      PIMCORE_INSTALL_MYSQL_USERNAME: "pimcore"
      PIMCORE_INSTALL_MYSQL_PASSWORD: "pimcore"
      PIMCORE_INSTALL_MYSQL_DATABASE: "pimcore"
    depends_on:
      - "db"
      - "redis"

  supervisord:
    image: "pimcore/pimcore:php8.3-supervisord-latest"
    volumes:
      - ".:/var/www/html:cached"
      - ".docker/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro"
    depends_on:
      - "db"

  mailpit:
    image: "axllent/mailpit"
    restart: "unless-stopped"
    volumes:
      - "mailpit-data:/data"
    ports:
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: "/data/mailpit.db"
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  database:
  redis-data:
  tmp-storage:
  mailpit-data:
