name: PHPStan

on: [push]

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    env:
      PIMCORE_TEST: 1
      APP_ENV: test
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: exif, gd, intl, xsl
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader --no-scripts

      - name: Install dependencies
        run: |
          bin/console pimcore:build:classes

      - name: Run phpstan
        uses: actions-x/phpstan@v1
        with:
          phpstanVersion: ^1.10
          level: 5
          paths: src tests
          useBundled: 1
          configPath: phpstan.neon.dist
          arguments: --memory-limit=1G