name: PHPStan

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          safe-directory: /app

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: xsl, gd, exif, intl, sodium

      - name: Install Composer dependencies
        uses: php-actions/composer@v6
        with:
          php_version: '8.3'
          args: --ignore-platform-reqs

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          path: src/
          level: 5
          configuration: phpstan.neon
          php_version: '8.3'
