name: PHPStan

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring

      - name: Download PHPStan
        run: |
          wget https://github.com/phpstan/phpstan/releases/download/1.10.50/phpstan.phar
          chmod +x phpstan.phar

      - name: Run PHPStan
        run: |
          PHP_VERSION=8.3 ./phpstan.phar analyse src/ --level=5 --configuration=phpstan.neon --no-progress
